-- CREACIÓN DEL USUARIO
CREATE USER proyecto_edt PASSWORD 'xD' LOGIN INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

-- CREACIÓN DEL TABLESPACE (OPCIONAL)
CREATE TABLESPACE ts_n9_proyecto_edt OWNER proyecto_edt LOCATION E'C:\\tablespaces\\n9_proyecto_edt';

-- CREACIÓN DE LA BASE DE DATOS
CREATE DATABASE proyecto_edt OWNER = proyecto_edt TABLESPACE = ts_n9_proyecto_edt;
